/*
 * Tyler Anderson
 * Mon Nov 12 13:50:19 EST 2012
 * These are error definitions
 */
#ifndef _BSD_ERR_H_
#define _BSD_ERR_H_

#define BSDUSB_OPEN_ERR 1
#define BSDUSB_SYS_FIND_BUSSES_ERR 2
#define BSDUSB_SYS_FIND_DEVICES_ERR 3
#define BSDUSB_FIND_DEVICE_ERR 4
#define BSDUSB_CLAIM_ERR 5
#define BSDUSB_ALTINTERFACE_ERR 6
#define BSDUSB_WRITE_ERR 7
#define BSDUSB_READ_ERR 8
#define BSDUSB_WRITE_TOO_MANY_BYTES_ERR 9

#define BSDCMD_CHECK_NOP_ERR 10
#define BSDCMD_CHECK_GET_ERR 11
#define BSDCMD_CHECK_SET_ERR 12
#define BSDCMD_CHECK_NODE_ERR 13
#define BSDCMD_CHECK_PARAM_ERR 14
#define BSDCMD_CHECK_HV_ERR 15
#define BSDCMD_CHECK_ROSTACK_ERR 16

#define BSDEVT_EVENT_BYTE_NUM_ERR 17

#define BSDCMD_CHECK_CLR_NODE_ERR 18
#define BSDCMD_CHECK_CLR_PARAM_ERR 19

#define BSDUSB_OPEN_IHX_FILE_ERR 20
#define BSDUSB_READ_IHX_FILE_ERR 21
#define BSDUSB_IHX_FORMAT_VIOLATION1_ERR 22
#define BSDUSB_IHX_FORMAT_VIOLATION2_ERR 23
#define BSDUSB_IHX_NBYTES_ERR 24
#define BSDUSB_IHX_FORMAT_VIOLATION3_ERR 25
#define BSDUSB_IHX_FORMAT_VIOLATION4_ERR 26
#define BSDUSB_CHECKSUM_ERR 27
#define BSDUSB_WRITE_RAM_ERR 28
#define BSDUSB_UNKNOWN_TYPE_ERR 29
#define BSDUSB_WRITE_RAM_CONNECTION_ERR 30
#define BSDUSB_RESET_FX2LP_ERR 31
#define BSDUSB_RESTART_FX2LP_ERR 32

#define BSDEVT_BAD_HEADER 33

#define BSDCMD_CHECK_DATAVAL_ERR 34
#define BSDCMD_EVENT_ERR 35
#define USB_SYNC_ERR 36
#define BSDCMD_ACTION_UNKNOWN_ERR 37

#endif
